language: node_js

node_js:
  - "node"
  - "9"

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t exide/top-down-arena-shooter .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" hub.docker.com;
    docker push exide/top-down-arena-shooter;
    fi
